apiVersion: v1
data:
  platformType: {{ default "OpenDataHub" .Values.platform.type | quote }}
  platformVersion: {{ default "" .Values.platform.version | quote }}
  {{- range $key, $val := .Values.config }}
  {{- if and (ne $key "platformType") (ne $key "platformVersion") }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-db-operator
  name: odh-db-operator-config
  namespace: {{ .Release.Namespace }}