apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-db-operator
  name: odh-db-operator-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: opendatahub-db-operator